name: q_flow
description: "TUWAIQ FLOW"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bootstrap_icons: ^1.11.3
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.8.0
  image_picker: ^1.1.2
  animated_snack_bar: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/onboarding/
    - assets/onboarding/onboarding_1.png
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 100
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 200
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 300
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 500
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 600
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 800
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 900

